In [3]:
%matplotlib inline

In [7]:
import sys
sys.path.append('../source')

import pandas as pd

import utilities as util
from constants import MOORING_DIRPATH, MOORING_FILEPATH, REANALYSIS_DIRPATH

# Rank Transports

I explore the ranking of total, wind and pressure head transports to answers reviewer questions.

__Was October 2016 (highest heat transport in the A3 record) one of the 15 high WINDtrans months? PHtrans?__

__Anything we can do here?__

__Line 282: I would be interested in seeing how the 15 high and low PHtrans and WINDtrans months are distributed among the overall distribution of TOTALtrans. For example if you sorted TOTALtrans plotting index vs transport, and then identified the max/min PHtrans and WINDtrans months, where would they rank? Are there peak PHtrans months that have below average TOTALtrans values?  It would also be nice to see where each of the case study months fall on this 'spectrum'.__

In [17]:
variable = ['HEAT', 'PH', 'WIND', 'TRANSPORT', 'TEMPERATURE']
column = ['MeanCorr', 'MeanCorr', 'MeanCorr', 'MeanCorr', 'Mean']
df = pd.concat([util.read_mooring(var, col) for var, col in zip(variable, column)], axis=1, keys=variables)

In [30]:
print(df.sort_values(by='HEAT', ascending=False).rank(ascending=False).iloc[0:15,:])

            HEAT     PH   WIND  TRANSPORT  TEMPERATURE
date
2016-10-01   1.0    NaN    NaN        1.0          1.0
2015-07-01   2.0    8.0   70.5        5.0         12.5
2007-09-01   3.0   80.0   27.0       26.5          9.0
2015-08-01   4.0   35.0  125.5       48.0          3.0
2011-07-01   5.0   44.0   37.5       16.5         24.0
2011-08-01   6.0   60.5   90.0       46.5         11.0
2017-06-01   7.0    NaN    NaN       16.5         22.5
2007-08-01   8.0   67.5   58.5       40.0         16.0
2007-07-01   9.0   23.0  114.0       26.5         25.0
1997-08-01  10.0  140.5   40.5       74.0          7.0
2004-08-01  11.5   93.0   39.0       44.5         26.0
2014-08-01  11.5   35.0   99.0       30.5         41.0
2011-10-01  13.0   98.5   49.5       60.0         18.5
2005-08-01  14.0  118.0   34.0       53.0         22.5
2011-06-01  15.5    6.5   54.0        4.0         81.0

In [28]:
df

            HEAT    PH  WIND  TRANSPORT  TEMPERATURE
date
1990-01-01   NaN   NaN   NaN        NaN          NaN
1990-02-01   NaN   NaN   NaN        NaN          NaN
1990-03-01   NaN   NaN   NaN        NaN          NaN
1990-04-01   NaN   NaN   NaN        NaN          NaN
1990-05-01   NaN   NaN   NaN        NaN          NaN
1990-06-01   NaN   NaN   NaN        NaN          NaN
1990-07-01   NaN   NaN   NaN        NaN          NaN
1990-08-01   NaN   NaN   NaN        NaN          NaN
1990-09-01   9.7   NaN   NaN       0.60         1.97
1990-10-01  10.2   NaN   NaN       0.62         1.45
1990-11-01   4.9   NaN   NaN       1.09        -0.48
1990-12-01   1.3   NaN   NaN       0.98        -1.63
1991-01-01   0.2  1.26 -0.75       0.51        -1.81
1991-02-01   0.0  0.74 -0.61       0.13        -1.84
1991-03-01   0.1  1.10 -0.51       0.59        -1.86
1991-04-01   0.2  1.07 -0.19       0.88        -1.84
1991-05-01   0.9  1.41 -0.21       1.20        -1.67
1991-06-01   9.6  1.73 -0.03       1.70        -0.50
1991-07-01  12.3  1.66 -0.18       1.48         0.10
1991-08-01  17.8  1.55 -0.03       1.52         1.07
1991-09-01  17.4   NaN   NaN       1.43         0.68
1991-10-01  13.6  0.94  0.10       1.04         1.62
1991-11-01  10.6  0.90  0.13       1.03         0.98
1991-12-01   0.3  0.58 -0.66      -0.08        -1.13
1992-01-01   0.7  1.48 -0.65       0.83        -1.70
1992-02-01   0.7  0.97 -0.02       0.95        -1.71
1992-03-01   0.5  1.11 -0.38       0.73        -1.73
1992-04-01   0.7  1.19 -0.16       1.03        -1.71
1992-05-01   2.9  0.94  0.18       1.12        -1.20
1992-06-01  12.9  1.18  0.02       1.20         0.66
...          ...   ...   ...        ...          ...
2015-07-01  40.1  1.88 -0.01       1.87         3.47
2015-08-01  31.6  1.54 -0.18       1.36         4.06
2015-09-01  13.3  0.92 -0.36       0.56         3.76
2015-10-01  22.1  1.15 -0.14       1.01         3.58
2015-11-01   4.2  0.72 -0.44       0.28         1.00
2015-12-01   1.1  1.17 -0.75       0.42        -1.39
2016-01-01   0.3  1.45 -1.09       0.36        -1.70
2016-02-01   0.7  1.78 -0.62       1.16        -1.75
2016-03-01   0.4  1.78 -1.04       0.74        -1.77
2016-04-01   0.5  1.80 -0.86       0.94        -1.76
2016-05-01   5.2  1.51  0.14       1.65        -1.16
2016-06-01  12.0  1.09 -0.09       1.00         1.01
2016-07-01  14.8   NaN   NaN       1.09         1.48
2016-08-01  10.4   NaN   NaN       0.77         1.52
2016-09-01  13.7   NaN   NaN       0.65         2.71
2016-10-01  56.4   NaN   NaN       2.03         5.35
2016-11-01  15.1   NaN   NaN       0.74         2.79
2016-12-01   7.5   NaN   NaN       1.21        -0.30
2017-01-01   1.4   NaN   NaN       0.48        -1.40
2017-02-01   0.2   NaN   NaN       0.35        -1.72
2017-03-01   0.5   NaN   NaN       1.09        -1.78
2017-04-01   1.2   NaN   NaN       1.44        -1.70
2017-05-01  13.7   NaN   NaN       1.45         0.46
2017-06-01  30.3   NaN   NaN       1.58         2.95
2017-07-01   NaN   NaN   NaN        NaN          NaN
2017-08-01   NaN   NaN   NaN        NaN          NaN
2017-09-01   NaN   NaN   NaN        NaN          NaN
2017-10-01   NaN   NaN   NaN        NaN          NaN
2017-11-01   NaN   NaN   NaN        NaN          NaN
2017-12-01   NaN   NaN   NaN        NaN          NaN

[336 rows x 5 columns]